#include <libbr/type_operate/add_rvalue_reference.hpp>

#include "test.hpp"

using namespace BR;

TEST(TypeOperate, AddRValueReference) {
	OPERATE_CHECKS(AddRValueReference, BR_EMPTY, &&)
	OPERATE_CHECKS(AddRValueReference, const, const &&)
	OPERATE_CHECKS(AddRValueReference, volatile, volatile &&)
	OPERATE_CHECKS(AddRValueReference, const volatile, const volatile &&)
	OPERATE_CHECKS(AddRValueReference, *, * &&)
	OPERATE_CHECKS(AddRValueReference, * const, * const &&)
	OPERATE_CHECKS(AddRValueReference, * volatile, * volatile &&)
	OPERATE_CHECKS(AddRValueReference, * const volatile, * const volatile &&)
	OPERATE_CHECKS(AddRValueReference, const *, const * &&)
	OPERATE_CHECKS(AddRValueReference, volatile *, volatile * &&)
	OPERATE_CHECKS(AddRValueReference, const * const, const * const &&)
	OPERATE_CHECKS(AddRValueReference, const * volatile, const * volatile &&)
	OPERATE_CHECKS(AddRValueReference, const * const volatile, const * const volatile &&)
	OPERATE_CHECKS(AddRValueReference, &, &)
	OPERATE_CHECKS(AddRValueReference, const &, const &)
	OPERATE_CHECKS(AddRValueReference, volatile &, volatile &)
	OPERATE_CHECKS(AddRValueReference, const volatile &, const volatile &)
	OPERATE_CHECKS(AddRValueReference, &&, &&)
	OPERATE_CHECKS(AddRValueReference, const &&, const &&)
	OPERATE_CHECKS(AddRValueReference, volatile &&, volatile &&)
	OPERATE_CHECKS(AddRValueReference, const volatile &&, const volatile &&)
	OPERATE_CHECKS(AddRValueReference, [2], (&&)[2])
	OPERATE_CHECKS(AddRValueReference, const[2], const(&&)[2])
	OPERATE_CHECKS(AddRValueReference, volatile[2], volatile(&&)[2])
	OPERATE_CHECKS(AddRValueReference, const volatile[2], const volatile(&&)[2])
	OPERATE_CHECKS(AddRValueReference, [2][3], (&&)[2][3])
	OPERATE_CHECKS(AddRValueReference, const[2][3], const(&&)[2][3])
	OPERATE_CHECKS(AddRValueReference, volatile[2][3], volatile(&&)[2][3])
	OPERATE_CHECKS(AddRValueReference, const volatile[2][3], const volatile(&&)[2][3])
	OPERATE_CHECKS(AddRValueReference, [][3], (&&)[][3])
	OPERATE_CHECKS(AddRValueReference, const[][3], const(&&)[][3])
	OPERATE_CHECKS(AddRValueReference, volatile[][3], volatile(&&)[][3])
	OPERATE_CHECKS(AddRValueReference, const volatile[][3], const volatile(&&)[][3])
	OPERATE_CHECKS(AddRValueReference, (&)[2], (&)[2])
	OPERATE_CHECKS(AddRValueReference, (&&)[2], (&&)[2])
	OPERATE_CHECKS(AddRValueReference, (&)[2][3], (&)[2][3])
	OPERATE_CHECKS(AddRValueReference, (&&)[2][3], (&&)[2][3])
}