image: gcc:6.0

before_script:
- env | sort
- cmake --version
cache:
  paths:
  - build/

build:g++6-debug-c++11:
  stage: build
  variables:
    CXX: 'g++-6'
    CC: 'gcc-6'
    BUILD_TYPE: 'debug'
    ENABLE_CXX14: 'OFF'
  script:
  - ${CXX} -v
  - ${CXX} --version
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLIBBR_ENABLE_CXX14=${ENABLE_CXX14} -DLIBBR_INCLUDE_TESTS=OFF -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CC_COMPILER=${CC} ${CI_PROJECT_DIR}
  - make br -j 2
  artifacts:
    paths:
    - build/libbr/libbr.a

build:g++6-debug-c++14:
  stage: build
  variables:
    CXX: 'g++-6'
    CC: 'gcc-6'
    BUILD_TYPE: 'debug'
    ENABLE_CXX14: 'ON'
  script:
  - ${CXX} -v
  - ${CXX} --version
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLIBBR_ENABLE_CXX14=${ENABLE_CXX14} -DLIBBR_INCLUDE_TESTS=OFF -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CC_COMPILER=${CC} ${CI_PROJECT_DIR}
  - make br -j 2
  artifacts:
    paths:
    - build/libbr/libbr.a

build:g++6-release-c++11:
  stage: build
  variables:
    CXX: 'g++-6'
    CC: 'gcc-6'
    BUILD_TYPE: 'release'
    ENABLE_CXX14: 'OFF'
  script:
  - ${CXX} -v
  - ${CXX} --version
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLIBBR_ENABLE_CXX14=${ENABLE_CXX14} -DLIBBR_INCLUDE_TESTS=OFF -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CC_COMPILER=${CC} ${CI_PROJECT_DIR}
  - make br -j 2
  artifacts:
    paths:
    - build/libbr/libbr.a

build:g++6-release-c++14:
  stage: build
  variables:
    CXX: 'g++-6'
    CC: 'gcc-6'
    BUILD_TYPE: 'release'
    ENABLE_CXX14: 'ON'
  script:
  - ${CXX} -v
  - ${CXX} --version
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLIBBR_ENABLE_CXX14=${ENABLE_CXX14} -DLIBBR_INCLUDE_TESTS=OFF -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_CC_COMPILER=${CC} ${CI_PROJECT_DIR}
  - make br -j 2
  artifacts:
    paths:
    - build/libbr/libbr.a

test:g++6-debug-c++11:
  stage: test
  script:
  - cd build
  - make br_test -j 2
  - ./test/br_test
  dependencies:
  - build:g++6-debug-c++11

test:g++6-debug-c++14:
  stage: test
  script:
  - cd build
  - make br_test -j 2
  - ./test/br_test
  dependencies:
  - build:g++6-debug-c++14

test:g++6-release-c++11:
  stage: test
  script:
  - cd build
  - make br_test -j 2
  - ./test/br_test
  dependencies:
  - build:g++6-release-c++11

test:g++6-release-c++14:
  stage: test
  script:
  - cd build
  - make br_test -j 2
  - ./test/br_test
  dependencies:
  - build:g++6-release-c++14
