# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc:5.0

variables:
  BUILD_TYPE: 'debug'
  ENABLE_CXX14: 'OFF'
cache:
  paths:
  - build/

build:
  stage: build
  # before_script: 
  # - apt update && apt -y install g++ g++-multilib cmake doxygen
  script:
  - env | sort
  - g++ -v
  - g++ --version
  - cmake --version
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLIBBR_ENABLE_CXX14=$ENABLE_CXX14 -DLIBBR_INCLUDE_TESTS=OFF $CI_PROJECT_DIR
  - cmake --build $CI_PROJECT_DIR/build --target br -- -j 8
  - cd $CI_PROJECT_DIR
  artifacts:
    paths:
    - build/*.a
# run tests using the binary built before
test:
 stage: test
 script:
 - env | sort
 - cmake --version
 - cmake --build build --target br_test -- -j 8
 - build/test/br_test
