before_script:
- env | sort
- cmake --version
variables:
  BUILD_ARGS: "-j 2"
cache:
  paths:
  - build/


.build: &build
  stage: build
  script:
  - ${CXX} -v
  - ${CXX} --version
  - mkdir -p "build/${CXX}-${BUILD_TYPE}-c++${CXX_STANDARD}" && cd "build/${CXX}-${BUILD_TYPE}-c++${CXX_STANDARD}"
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLIBBR_CXX_STANDARD=${CXX_STANDARD} ${CI_PROJECT_DIR}
  - cmake --build . --target br -- ${BUILD_ARGS}
  artifacts:
    paths:
    - ${CI_JOB_NAME}/libbr/libbr.a
.test: &test
  stage: test
  script:
  - cd "build/${CXX}-${BUILD_TYPE}-c++${CXX_STANDARD}"
  - cmake --build . --target br_test -- ${BUILD_ARGS}
  - ./test/br_test


.variables: &variables
  CXX: 'g++-6'
  CC: 'gcc-6'
  BUILD_TYPE: 'debug'
  CXX_STANDARD: '11'
build/g++-6-debug-c++11:
  <<: *build
  variables:
    <<: *variables
test/g++-6-debug-c++11:
  <<: *test
  variables:
    <<: *variables
  dependencies:
  - build/g++-6-debug-c++11


.variables: &variables
  CXX: 'g++-6'
  CC: 'gcc-6'
  BUILD_TYPE: 'debug'
  CXX_STANDARD: '14'
build/g++-6-debug-c++14:
  <<: *build
  variables:
    <<: *variables
test/g++-6-debug-c++14:
  <<: *test
  variables:
    <<: *variables
  dependencies:
  - build/g++-6-debug-c++14


.variables: &variables
  CXX: 'g++-6'
  CC: 'gcc-6'
  BUILD_TYPE: 'release'
  CXX_STANDARD: '11'
build/g++-6-release-c++11:
  <<: *build
  variables:
    <<: *variables
test/g++-6-release-c++11:
  <<: *test
  variables:
    <<: *variables
  dependencies:
  - build/g++-6-release-c++11


.variables: &variables
  CXX: 'g++-6'
  CC: 'gcc-6'
  BUILD_TYPE: 'release'
  CXX_STANDARD: '14'
build/g++-6-release-c++14:
  <<: *build
  variables:
    <<: *variables
test/g++-6-release-c++14:
  <<: *test
  variables:
    <<: *variables
  dependencies:
  - build/g++-6-release-c++14


.variables: &variables
  CXX: 'clang++-4.0'
  CC: 'clang-4.0'
  BUILD_TYPE: 'debug'
  CXX_STANDARD: '11'
build/clang++-4.0-debug-c++11:
  <<: *build
  variables:
    <<: *variables
test/clang++-4.0-debug-c++11:
  <<: *test
  variables:
    <<: *variables
  dependencies:
  - build/clang++-4.0-debug-c++11


.variables: &variables
  CXX: 'clang++-4.0'
  CC: 'clang-4.0'
  BUILD_TYPE: 'debug'
  CXX_STANDARD: '14'
build/clang++-4.0-debug-c++14:
  <<: *build
  variables:
    <<: *variables
    CXX_STANDARD: '14'
test/clang++-4.0-debug-c++14:
  <<: *test
  variables:
    <<: *variables
  dependencies:
  - build/clang++-4.0-debug-c++14


.variables: &variables
  CXX: 'clang++-4.0'
  CC: 'clang-4.0'
  BUILD_TYPE: 'release'
  CXX_STANDARD: '11'
build/clang++-4.0-release-c++11:
  <<: *build
  variables:
    <<: *variables
test/clang++-4.0-release-c++11:
  <<: *test
  variables:
    <<: *variables
  dependencies:
  - build/clang++-4.0-release-c++11


.variables: &variables
  CXX: 'clang++-4.0'
  CC: 'clang-4.0'
  BUILD_TYPE: 'release'
  CXX_STANDARD: '14'
build/clang++-4.0-release-c++14:
  <<: *build
  variables:
    <<: *variables
test/clang++-4.0-release-c++14:
  <<: *test
  variables:
    <<: *variables
  dependencies:
  - build/clang++-4.0-release-c++14