language: cpp
os:
- linux
- osx
compiler:
- gcc
- clang
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - gcc-4.9
    - clang-3.7
    - valgrind
    - libgtest-dev
env:
  matrix:
  - LIBBR_TARGET=Debug-11-32   BUILD_TYPE=debug   ENABLE_CXX14=OFF BUILD_32_BITS=ON  VERBOSE_MAKE=true VERBOSE
  - LIBBR_TARGET=Debug-11-64   BUILD_TYPE=debug   ENABLE_CXX14=OFF BUILD_32_BITS=OFF VERBOSE_MAKE=true VERBOSE
  - LIBBR_TARGET=Debug-14-32   BUILD_TYPE=debug   ENABLE_CXX14=ON  BUILD_32_BITS=ON  VERBOSE_MAKE=true VERBOSE
  - LIBBR_TARGET=Debug-14-64   BUILD_TYPE=debug   ENABLE_CXX14=ON  BUILD_32_BITS=OFF VERBOSE_MAKE=true VERBOSE
  - LIBBR_TARGET=Release-11-32 BUILD_TYPE=release ENABLE_CXX14=OFF BUILD_32_BITS=ON  VERBOSE_MAKE=true VERBOSE
  - LIBBR_TARGET=Release-11-64 BUILD_TYPE=release ENABLE_CXX14=OFF BUILD_32_BITS=OFF VERBOSE_MAKE=true VERBOSE
  - LIBBR_TARGET=Release-14-32 BUILD_TYPE=release ENABLE_CXX14=ON  BUILD_32_BITS=ON  VERBOSE_MAKE=true VERBOSE
  - LIBBR_TARGET=Release-14-64 BUILD_TYPE=release ENABLE_CXX14=ON  BUILD_32_BITS=OFF VERBOSE_MAKE=true VERBOSE
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
script:
- mkdir build || true
- mkdir build/$LIBBR_TARGET || true
- cd build/$LIBBR_TARGET
- cmake -DLIBBR_ENABLE_CXX14=$ENABLE_CXX14 -DLIBBR_BUILD_32_BITS=$BUILD_32_BITS ../../
- cmake --build . --target br_test -- -j 8
- ./test/br_test.exe
sudo: false