language: cpp
compiler:
- gcc
- clang
os:
- linux
#- osx
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
    packages:
    - cmake
env:
  matrix:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
before_install:
# Install gtest.
- wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
- tar xf release-1.8.0.tar.gz && cd googletest-release-1.8.0/googletest
- cmake .
- make
- export GTEST_ROOT="`pwd`"
- cd $TRAVIS_BUILD_DIR
install:
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-5 g++-5-multilib && export CXX="g++-5" CC="gcc-5"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -qq clang-3.7 && export CXX="clang++-3.7" CC="clang-3.7"; fi
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
script:
- mkdir -p build && cd build
# C++11
- cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLIBBR_ENABLE_CXX14=OFF $TRAVIS_BUILD_DIR
- cmake --build . --target br_test -- -j 8
- ./test/br_test
# C++14
- cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLIBBR_ENABLE_CXX14=ON  $TRAVIS_BUILD_DIR
- cmake --build . --target br_test -- -j 8
- ./test/br_test
sudo: true
notifications:
  email: false