language: cpp
os:
- linux
- osx
compiler:
- gcc
- clang
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-4.9
    - clang-3.7
env:
  matrix:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
before_install:
- wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
- tar xf release-1.8.0.tar.gz
- cd googletest-release-1.8.0
- mkdir build || true
- cd build
- cmake -DBUILD_SHARED_LIBS=ON ../
- make
- cp lib*.so ~/usr/gtest/lib
- cd ..
- cp -r googletest/include/gtest/ ~/usr/gtest/include/
- cd ..
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
script:
- set -evx
- env | sort
- mkdir build || true
- cd build
# C++11 32bits
- cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLIBBR_ENABLE_CXX14=OFF -DLIBBR_BUILD_32_BITS=ON  ../../
- cmake --build . --target br_test -- -j 8 && ./test/br_test.exe
# C++11 64bits
- cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLIBBR_ENABLE_CXX14=OFF -DLIBBR_BUILD_32_BITS=OFF ../../
- cmake --build . --target br_test -- -j 8 && ./test/br_test.exe
# C++14 32bits
- cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLIBBR_ENABLE_CXX14=ON  -DLIBBR_BUILD_32_BITS=ON  ../../
- cmake --build . --target br_test -- -j 8 && ./test/br_test.exe
# C++14 64bits
- cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DLIBBR_ENABLE_CXX14=ON  -DLIBBR_BUILD_32_BITS=OFF ../../
- cmake --build . --target br_test -- -j 8 && ./test/br_test.exe
sudo: false